# theme: jekyll-theme-midnight
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Scry CLI
description: A command line tool for exploring your file system.
logo: ./assets/img/logo.png
show_downloads: true
