name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

#     - name: Build
#       run: go build -v ./...

    - name: Test
      run: go test -coverprofile=coverage.out -covermode=count  ./...

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Publish Code Coverage Badge
      run: |
        set -x
        total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        if (( $(echo "$total < 20" | bc -l) )) ; then
          COLOR=red
        elif (( $(echo "$total < 40" | bc -l) )); then
          COLOR=orange
        elif (( $(echo "$total < 70" | bc -l) )); then
          COLOR=yellow
        else
          COLOR=green
        fi
        curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > badge.svg
        gsutil  -h "Cache-Control: no-cache" cp badge.svg gs://scry-build/code-coverage.svg
        gsutil acl ch -u AllUsers:R gs://scry-build/code-coverage.svg
